### ISSUE TITLE
Mangazuki Cloudflare

### ISSUE THREAD

**Issue by Vesnyx** [DakuTree/manga-tracker#203] opened 2017-09-10 02:23 UTC
This might be causing issues. The one series I'm following from them says it's been unable to update for the last few days.

**Comment by DakuTree** [comment] 2017-09-10 08:12
Yeah, Cloudflare protection seems to be the cause here.  
For now I've went and disabled the site so we don't end up getting IP banned (like we did with KissManga).

Need to try and find a permenant solution for this incase more sites start to use it.  
[cloudflare-scrape](https://github.com/Anorov/cloudflare-scrape) seems to be the best option but it uses since it uses Python it might need a bit of trickery to get working well.

**Comment by DakuTree** [comment] 2017-09-15 19:57
The DDOS protection appears to have been disabled now so I've re-enabled the site. Series should update shortly.

Will leave this issue open as it does appear the site still uses Cloudflare, so we might need to change to using cloudflare-scrape later on.

**Comment by DakuTree** [comment] 2017-11-28 22:39
Closing as we now have CloudFlare support.

**Closed by DakuTree** 2017-11-28 22:39 UTC
Labels: bug, partial-fix, Site Support
